export const customers = [
  {
    id: 1,
    CompanyName: "Super Mart of the West",
    Address: "702 SW 8th Street",
    City: "Bentonville",
    State: "Arkansas",
    Zipcode: 72716,
    Phone: "(800) 555-2797",
    Fax: "(800) 555-2171",
  },
  {
    id: 2,
    CompanyName: "Electronics Depot",
    Address: "2455 Paces Ferry Road NW",
    City: "Atlanta",
    State: "Georgia",
    Zipcode: 30339,
    Phone: "(800) 595-3232",
    Fax: "(800) 595-3231",
  },
  {
    id: 3,
    CompanyName: "K&S Music",
    Address: "1000 Nicllet Mall",
    City: "Minneapolis",
    State: "Minnesota",
    Zipcode: 55403,
    Phone: "(612) 304-6073",
    Fax: "(612) 304-6074",
  },
  {
    id: 4,
    CompanyName: "Tom's Club",
    Address: "999 Lake Drive",
    City: "Issaquah",
    State: "Washington",
    Zipcode: 98027,
    Phone: "(800) 955-2292",
    Fax: "(800) 955-2293",
  },
  {
    id: 5,
    CompanyName: "E-Mart",
    Address: "3333 Beverly Rd",
    City: "Hoffman Estates",
    State: "Illinois",
    Zipcode: 60179,
    Phone: "(847) 286-2500",
    Fax: "(847) 286-2501",
  },
  {
    id: 6,
    CompanyName: "Walters",
    Address: "200 Wilmot Rd",
    City: "Deerfield",
    State: "Illinois",
    Zipcode: 60015,
    Phone: "(847) 940-2500",
    Fax: "(847) 940-2501",
  },
  {
    id: 7,
    CompanyName: "StereoShack",
    Address: "400 Commerce S",
    City: "Fort Worth",
    State: "Texas",
    Zipcode: 76102,
    Phone: "(817) 820-0741",
    Fax: "(817) 820-0742",
  },
  {
    id: 8,
    CompanyName: "Circuit Town",
    Address: "2200 Kensington Court",
    City: "Oak Brook",
    State: "Illinois",
    Zipcode: 60523,
    Phone: "(800) 955-2929",
    Fax: "(800) 955-9392",
  },
  {
    id: 9,
    CompanyName: "Premier Buy",
    Address: "7601 Penn Avenue South",
    City: "Richfield",
    State: "Minnesota",
    Zipcode: 55423,
    Phone: "(612) 291-1000",
    Fax: "(612) 291-2001",
  },
  {
    id: 10,
    CompanyName: "ElectrixMax",
    Address: "263 Shuman Blvd",
    City: "Naperville",
    State: "Illinois",
    Zipcode: 60563,
    Phone: "(630) 438-7800",
    Fax: "(630) 438-7801",
  },
  {
    id: 11,
    CompanyName: "Video Emporium",
    Address: "1201 Elm Street",
    City: "Dallas",
    State: "Texas",
    Zipcode: 75270,
    Phone: "(214) 854-3000",
    Fax: "(214) 854-3001",
  },
  {
    id: 12,
    CompanyName: "Screen Shop",
    Address: "1000 Lowes Blvd",
    City: "Mooresville",
    State: "North Carolina",
    Zipcode: 28117,
    Phone: "(800) 445-6937",
    Fax: "(800) 445-6938",
  },
];

// users
export const users = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    age: 25,
    email: "john.doe@example.com",
    city: "New York",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    age: 30,
    email: "jane.smith@example.com",
    city: "Los Angeles",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    age: 28,
    email: "michael.brown@example.com",
    city: "Chicago",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Johnson",
    age: 22,
    email: "emily.johnson@example.com",
    city: "Houston",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Wilson",
    age: 35,
    email: "david.wilson@example.com",
    city: "Phoenix",
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Williams",
    age: 29,
    email: "sarah.williams@example.com",
    city: "Philadelphia",
  },
  {
    id: 7,
    firstName: "Chris",
    lastName: "Jones",
    age: 27,
    email: "chris.jones@example.com",
    city: "San Antonio",
  },
  {
    id: 8,
    firstName: "Laura",
    lastName: "Garcia",
    age: 31,
    email: "laura.garcia@example.com",
    city: "San Diego",
  },
  {
    id: 9,
    firstName: "Daniel",
    lastName: "Martinez",
    age: 33,
    email: "daniel.martinez@example.com",
    city: "Dallas",
  },
  {
    id: 10,
    firstName: "Natalie",
    lastName: "Clark",
    age: 26,
    email: "natalie.clark@example.com",
    city: "San Jose",
  },
  {
    id: 11,
    firstName: "Gwen",
    lastName: "Graham",
    age: 29,
    email: "gwen.graham@example.com",
    city: "Gwenborough",
  },
  {
    id: 12,
    firstName: "Ervin",
    lastName: "Howell",
    age: 32,
    email: "ervin.Howell@example.com",
    city: "Wisokyburgh",
  },
  {
    id: 13,
    firstName: "Patricia",
    lastName: "Lebsack",
    age: 36,
    email: "patricia.Lebsack@example.com",
    city: "South Elvis",
  },
  {
    id: 14,
    firstName: "Dennis",
    lastName: "Schulist",
    age: 25,
    email: "dennis.schulist@example.com",
    city: "South Christy",
  },
  {
    id: 15,
    firstName: "Glenna",
    lastName: "Reichert",
    age: 29,
    email: "glenna.reichert@example.com",
    city: "Detroit",
  },
];
